mimic:
  path: data/mimic
  classes: [-1, 0, 1, 2]
  findings: [
    "Atelectasis", "Cardiomegaly", "Consolidation",
    "Edema", "Enlarged Cardiomediastinum", "Fracture",
    "Lung Lesion", "Lung Opacity", #"No Finding",
    "Pleural Effusion", "Pleural Other", "Pneumonia",
    "Pneumothorax", "Support Devices",
  ]
  language: English

mimic_translated:
  path: data/mimic_translated
  classes: [-1, 0, 1, 2]
  findings: [
    "Atelectasis", "Cardiomegaly", "Consolidation",
    "Edema", "Enlarged Cardiomediastinum", "Fracture",
    "Lung Lesion", "Lung Opacity", #"No Finding",
    "Pleural Effusion", "Pleural Other", "Pneumonia",
    "Pneumothorax", "Support Devices",
  ]
  language: English

padchest:
  path: data/padchest
  classes: [-1, 1]
  findings: [
    'air trapping', 'alveolar pattern', 'aortic atheromatosis',
    'aortic button enlargement', 'aortic elongation', 'apical pleural thickening',
    'atelectasis', 'bronchiectasis', 'bronchovascular markings',
    'calcified densities', 'calcified granuloma', 'callus rib fracture',
    'cardiomegaly', 'central venous catheter via jugular vein', 'chronic changes',
    'consolidation', 'costophrenic angle blunting', 'diaphragmatic eventration',
    'dual chamber device', 'endotracheal tube', 'fibrotic band', 'flattened diaphragm',
    'goiter', 'gynecomastia', 'hemidiaphragm elevation', 'hiatal hernia',
    'hilar congestion', 'hilar enlargement', 'increased density',
    'infiltrates', 'interstitial pattern', 'kyphosis', 'laminar atelectasis',
    'mammary prosthesis', 'metal', 'nipple shadow', #'no finding',
    'nodule', 'nsg tube', 'osteosynthesis material', 'pacemaker',
    'pleural effusion', 'pseudonodule', 'scoliosis', 'sternotomy',
    'suture material', 'vascular hilar enlargement', 'vertebral anterior compression',
    'vertebral degenerative changes', 'volume loss'
  ]
  language: Spanish

padchest_EN:
  path: data/padchest_EN
  classes: [-1, 1]
  findings: [
    'air trapping', 'alveolar pattern', 'aortic atheromatosis',
    'aortic button enlargement', 'aortic elongation', 'apical pleural thickening',
    'atelectasis', 'bronchiectasis', 'bronchovascular markings',
    'calcified densities', 'calcified granuloma', 'callus rib fracture',
    'cardiomegaly', 'central venous catheter via jugular vein', 'chronic changes',
    'consolidation', 'costophrenic angle blunting', 'diaphragmatic eventration',
    'dual chamber device', 'endotracheal tube', 'fibrotic band', 'flattened diaphragm',
    'goiter', 'gynecomastia', 'hemidiaphragm elevation', 'hiatal hernia',
    'hilar congestion', 'hilar enlargement', 'increased density',
    'infiltrates', 'interstitial pattern', 'kyphosis', 'laminar atelectasis',
    'mammary prosthesis', 'metal', 'nipple shadow', #'no finding',
    'nodule', 'nsg tube', 'osteosynthesis material', 'pacemaker',
    'pleural effusion', 'pseudonodule', 'scoliosis', 'sternotomy',
    'suture material', 'vascular hilar enlargement', 'vertebral anterior compression',
    'vertebral degenerative changes', 'volume loss'
  ]
  language: English

casia:
  path: data/casia
  classes: [-1, 1]
  findings: [
    'cardiomegaly', 'mass', 'pleuraleffusion',
    'pneumonia', 'pneumothorax'
  ]
  language: French


danskcxr:
  path: data/danskcxr
  classes: [-1, 1, 2]
  findings: [
    'Atelectasis', 'Cardiomegaly', 'ChronicLungChanges', 
    'Consolidation', 'Fracture', 'IncreasedInterstitial', 
    'Infiltrate', 'LungDecreasedTranslucency', 'NoduleTumorMass', 
    'PleuralEffusion', 'PneumoniaInfection', 'Pneumothorax', 
    'StasisEdema', 'SupportDevices'
  ]
  language: Danish

danskcxr_translated:
  path: data/danskcxr_translated
  classes: [-1, 1, 2]
  findings: [
    'Abscess', 'Aneurysm', 'Asbestosis',
    'Aspergillosis', 'Atelectasis', 'Cardiomegaly', 
    'CavitaryLesion', 'ChronicLungChanges', 'Consolidation',
    'CorrectPlacement', 'CystBullae', 'DiffuseInfiltrate',
    'ElevatedHemidiaphragm', 'Emphysema', 'EnlargedMediastinum',
    'Fibrosis', 'FlattenedDiaphragm', 'FocalInfiltrate',
    'Fracture', 'HiatusHernia', 'IncreasedInterstitial',
    'Infiltrate', 'InterlobarThickening', 'LungDecreasedTranslucency',
    'LungIncreasedTranslucency', 'LungSurgery', 'LymphNodePathology',
    'MalignantCancer', 'MediastinalShift', 'MediastinalTumor',
    'NoduleTumorMass', 'NotCorrectPlacement', 'OperationImplants',
    'PericardialEffusion', 'PleuralCalcification', 'PleuralChanges',
    'PleuralContraction', 'PleuralEffusion', 'PleuralThickening',
    'Pneumomediastinum', 'PneumoniaInfection', 'Pneumothorax',
    'Sarcoidosis', 'StasisEdema', 'SubcutaneousEmphysema',
    'SupportDevices', 'Tuberculosis', 'VascularChanges'
  ]

reflacx_i:
  path: data/reflacx_i
  classes: [-1, 0, 1]
  findings: [
    'Airway wall thickening',  'Atelectasis',  'Consolidation', 
    'Emphysema', 'Enlarged cardiac silhouette',  'Fibrosis', 
    'Fracture', 'Groundglass opacity', 'Mass', 
    'Nodule',  'Pleural effusion', 'Pleural thickening', 
    'Pneumothorax',  'Pulmonary edema', 'Wide mediastinum'
  ]
  language: English

reflacx_ii:
  path: data/reflacx_ii
  classes: [-1, 0, 1]
  findings: [
    'Abnormal mediastinal contour',  'Acute fracture',  'Atelectasis',
    'Consolidation',  'Enlarged cardiac silhouette',  'Enlarged hilum',
    'Groundglass opacity',  'Hiatal hernia', 'High lung volume / emphysema',
    'Interstitial lung disease',  'Lung nodule or mass', 'Pleural abnormality', 
    'Pneumothorax', 'Pulmonary edema'
  ]
  language: English

bd5:
  path: data/bd5
  classes: [-1, 0, 1]
  findings: [
    'Focal Cortical Dysplasia',
    'Hippocampal Abnormalities',
    'Mesial Temporal Sclerosis'
  ]

bd5_translated:
  path: data/bd5_translated
  classes: [-1, 0, 1]
  findings: [
    'Focal Cortical Dysplasia',
    'Hippocampal Abnormalities',
    'Mesial Temporal Sclerosis'
  ]

danskmri:
  path: data/danskmri
  classes: [-1, 1]
  findings: [
    'encephalocele',
    'focal cortical dysplasia',
    'hamartoma',
    'hemimegalencephaly',
    'heterotopia',
    'lissencephaly',
    'polymicrogyria',
    'schizencephaly',
    'tuberous sclerosis'
  ]
  language: Danish
